server:
  port: 9090

  servlet:
    context-path: /api


spring:
  application:
    name: ALaOrdenApi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost/TFinal
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver