export const VIEW_TASK_LIST = 'VIEW_TASK_LIST';

export const VIEW_BALANCE_LIST = 'VIEW_BALANCE_LIST';
export const EXECUTE_TRANSFER = 'EXECUTE_TRANSFER';

//--------------------------

export const VIEW_CATEGORIA_LIST = 'VIEW_CATEGORIA_LIST';
export const SAVE_CATEGORIA='SAVE_CATEGORIA';

export const VIEW_SUBCATEGORIA_LIST = 'VIEW_SUBCATEGORIA_LIST';
export const SAVE_SUBCATEGORIA = 'SAVE_SUBCATEGORIA';

export const VIEW_PRODUCTO_LIST = 'VIEW_PRODUCTO_LIST';
export const SAVE_PRODUCTO = 'SAVE_PRODUCTO';


export const VIEW_ORDEN_LIST='VIEW_ORDEN_LIST';
export const SAVE_ORDEN = 'SAVE_ORDEN';

export const VIEW_DETALLEORDEN_LIST='VIEW_ORDEN_LIST';
export const SAVE_DETALLEORDEN = 'SAVE_ORDEN';

export const DELETE_PRODUCTO = 'DELETE_PRODUCTO'

export const DELETE_CATEGORIA = 'DELETE_CATEGORIA'


export const DELETE_SUBCATEGORIA= 'DELETE_SUBCATEGORIA'