export const VIEW_TASK_LIST = 'VIEW_TASK_LIST';

export const VIEW_BALANCE_LIST = 'VIEW_BALANCE_LIST';
export const EXECUTE_TRANSFER = 'EXECUTE_TRANSFER';

//--------------------------

export const VIEW_CATEGORIA_LIST = 'VIEW_CATEGORIA_LIST';
export const SAVE_CATEGORIA='SAVE_CATEGORIA';

export const VIEW_SUBCATEGORIA_LIST = 'VIEW_SUBCATEGORIA_LIST';
export const SAVE_SUBCATEGORIA = 'SAVE_SUBCATEGORIA';

export const VIEW_PRODUCTO_LIST = 'VIEW_PRODUCTO_LIST';
export const SAVE_PRODUCTO = 'SAVE_PRODUCTO';


export const VIEW_PEDIDO_LIST='VIEW_PEDIDO_LIST';
export const SAVE_PEDIDO = 'SAVE_PEDIDO';

export const VIEW_DETALLEPEDIDO_LIST='VIEW_PEDIDO_LIST';
export const SAVE_DETALLEPEDIDO = 'SAVE_PEDIDO';

export const DELETE_PRODUCTO = 'DELETE_PRODUCTO'

export const DELETE_CATEGORIA = 'DELETE_CATEGORIA'


export const DELETE_SUBCATEGORIA= 'DELETE_SUBCATEGORIA'

export const VIEW_CUPON_LIST = 'VIEW_CUPON_LIST';
export const SAVE_CUPON = 'SAVE_CUPON';

export const DELETE_CUPON = 'DELETE_CUPON'